# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhidaily', '0004_auto_20161119_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_time',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
