# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhidaily', '0006_best_sort'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='AD')),
                ('url', models.URLField()),
            ],
        ),
    ]
