# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhidaily', '0008_advert_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
