# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhidaily', '0010_auto_20161123_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='url',
            field=models.URLField(blank=True, default='#', null=True),
        ),
    ]
